fix: update token for auto upgrade workflow (#40)
We are currently seeing errors during our `upgrade dependencies auto upgrade workflow` like,

```
Error: Unprocessable Entity: "Can not approve your own pull request". This typically happens when you try to approve the pull request with the same user account that created the pull request. Try using the built-in `${{ secrets.GITHUB_TOKEN }}` token, or if you're using a personal access token, use one that belongs to a dedicated bot account.
```

This PR is updating the secret being currently used for auto upgrade workflow.

Signed-off-by: Vinayak Kukreja <vinakuk@amazon.com>